import type { Metadata } from "next";
import { Inter, Lilita_One, Silkscreen, Lexend} from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const lilitaOne = Lilita_One({ subsets: ["latin"], weight: "400", variable: "--font-lilita-one"});
const silkscreen = Silkscreen({ subsets: ["latin"], weight: ["400", "700"], variable: "--font-silkscreen"});
const lexend = Lexend({subsets: ["latin"], weight:["400","900"], variable:"--font-lexend"})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={`${lilitaOne.variable} ${silkscreen.variable} ${lexend.variable}`}>{children}</body>
    </html>
  );
}
